### ISSUE TITLE
Version for torch,torch_geometric,pyscipopt

### ISSUE THREAD

**Issue by piquepq** [ds4dm/learn2comparenodes#1]
Can you show the version for torch,torch_geometric,pyscipopt,especially for pyscipopt.It will be better if you can show how to install these library.I meet lost of problem for installing these libraries!

**Comment by piquepq** [comment]
Exception ignored in: 'pyscipopt.scip.PyNodeselComp'
Traceback (most recent call last):
  File "compare/node_selection/behaviour_gen.py", line 46, in nodecomp
    comp_res, comp_type = super().nodecomp(node1, node2, return_type=True)
  File "compare/node_selection/node_selectors.py", line 193, in nodecomp
    d1 = self.is_sol_in_domaine(self.optsol, node1)
  File "compare/node_selection/node_selectors.py", line 223, in is_sol_in_domaine
    bvars, bbounds, btypes = node.getAncestorBranchings()
AttributeError: 'pyscipopt.scip.Node' object has no attribute 'getAncestorBranchings'
------------------------------------------------------------------------------------------------------------------------------------------------

This is the problem when I run behaviour_gen.py

**Comment by hongxuanrui1999** [comment]
May be you can try cd the pyscipopt path in this program and python -m pip install . to solve the problem. The authors modified the pyscipopt source code to adapt their model and you should install their version.
